spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://rm-bp1u33k088xm340146o.mysql.rds.aliyuncs.com:3306/foq?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost/foq20180625?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://27.223.92.198/foq?characterEncoding=utf-8&useSSL=false
    username: root
    password: YuCn@1227
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    open-in-view: true
server:
  context-path: /foq
  port: 8888

